#ifndef LIBMASTODON_GLOBAL_H
#define LIBMASTODON_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBMASTODON_LIBRARY)
#  define LIBMASTODONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBMASTODONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBMASTODON_GLOBAL_H
